// Auto-generated by scripts/build-live-data.mjs — do not edit by hand.
// Live Trooth bundle (ingest + scorer + official actuals). source: "live".

import live from "./generated/liveBundle.json" with { type: "json" };

export const DOMAINS = ["Finance", "Sports", "Weather", "Politics"];

export const CATCOLORS = {
  Finance: { color: "#1F6F5C", tint: "#E3EFEA" },
  Sports: { color: "#B4571F", tint: "#F6E9DE" },
  Weather: { color: "#2E6BA6", tint: "#E1EBF4" },
  Politics: { color: "#9A3B5A", tint: "#F4E4EA" },
};

// Official-print allowlist (schema v1.1.0). Politics: SOS / FEC / congress.gov only.
export const OFFICIAL_PRINT = {
  // Architect ruling 3 (2026-10-04): graded cards use the source recorded on the actual; this is the
  // ungraded placeholder only (no host guessed).
  finance: { name: "Official government release or listing exchange close", url: "/method" },
  weather: { name: "NWS", url: "https://api.weather.gov/stations/KNYC/observations" },
  sports: { name: "NFL official box score", url: "https://www.nfl.com/scores/" },
  politics: { name: "FEC certified canvass", url: "https://www.fec.gov/" },
};

export const SUBJECTS = live.SUBJECTS;
export const SPEAKERS = live.SPEAKERS;
export const FORECASTS = live.FORECASTS;
export const ACTUALS = live.ACTUALS;
export const SCORES = live.SCORES;
export const DATA_SOURCE = live.source || "live";
export const GENERATED_AT = live.generated_at || null;
