// Plain-English labels for reason codes shown to readers (changelog-v1.md "Public page rules" §4).
// GENERATED by scripts/gen-reason-labels.mjs from /workspace/trooth/reason-labels-v1.md — do not edit by hand.
// Canonical copy: Architect-approved v1.0.0 (2026-09-25). To change a label, edit that file and regenerate.
//
// The raw code stays in the data and in the page source (title attribute) so it can be audited.
// Aliases (retired codes) render the canonical code's label. A code with no entry renders raw (never guessed).

export const REASON_LABELS_VERSION = "1.0.0";

export const REASON_LABELS = {
  "qualitative": { label: "not a measurable claim", where: ["unscorable_reason","skipped"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "sarcastic": { label: "said sarcastically, not a real forecast", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "hedged": { label: "hedged, no firm call", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "no_horizon": { label: "no date or deadline given", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "no_explicit_value": { label: "no specific number or pick", where: ["unscorable_reason","skipped"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "no_attributable_source": { label: "can't be traced to the speaker", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "unit_unknown": { label: "unclear what is being measured", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "enum_unknown": { label: "team or player not in our list", where: ["unscorable_reason"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "schema-v1" },
  "no_official_print": { label: "no official result to grade against", where: ["unscorable_reason","subject resolution","score rationale"], shown: "Yes: claim card: Actual and Actual source lines, as \"None (label)\"", spec: "equity-analyst-subjects-v1 (non-schema)" },
  "needs_review": { label: "under review", where: ["score status void"], shown: "Yes: /changelog In review entries (default reason for voids[])", spec: "rubric-v1" },
  "missed_key": { label: "no matching official result found yet", where: ["review queue"], shown: "Not today (internal data); label ready if it ever goes public", spec: "rubric-v1 (non-schema code)" },
  "attribution_under_review": { label: "who said it is being re-checked", where: ["score review_hold","review queue"], shown: "Yes: claim card: after the \"In review\" grade", spec: "scorer holds.jsonl (non-schema code)" },
  "unofficial_candidate": { label: "unofficial number, not used for grading", where: ["scorer log"], shown: "Not today (internal data); label ready if it ever goes public", spec: "rubric-v1" },
  "legal_scope": { label: "adjusted to fit our source-use rules", where: ["changelog corrections"], shown: "Yes: /changelog entry", spec: "changelog-v1" },
  "horizon_end_corrected": { label: "deadline corrected", where: ["changelog errors (correction)"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "horizon_end_session_roll": { label: "deadline moved to the next trading day", where: ["changelog errors (correction)"], shown: "Not today (internal data); label ready if it ever goes public", spec: "equity-analyst-subjects-v1 (non-schema code)" },
  "retracted_u1_aggregator_rating": { aliasOf: "rating_not_in_broker_wording", where: ["changelog"], shown: "renders as canonical label", spec: "Architect 2026-09-25" },
  "deadline_moved_to_trading_day": { aliasOf: "horizon_end_session_roll", where: ["changelog corrections"], shown: "renders as canonical label", spec: "Architect 2026-09-25" },
  "rating_not_in_broker_wording": { label: "removed: rating not in the broker's own wording", where: ["changelog retractions"], shown: "Yes: /changelog entry", spec: "us-equity-analyst-rating-ids-v1 rule U1 (non-schema code, changelog 2026-09-25)" },
  "duplicate_forecast_cross_outlet": { label: "same call already recorded from another outlet", where: ["changelog skipped (retracted before publish)"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "duplicate": { label: "duplicate of a claim already recorded", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "changelog-v1" },
  "not_a_forecast": { label: "not a forecast", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "changelog-v1" },
  "subject_not_in_registry": { label: "topic not tracked yet", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "changelog-v1" },
  "12_hour_band": { label: "12-hour rain range, not a daily total", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "dual_hold": { label: "two scorelines depending on a condition", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema (CB-004)" },
  "published_after_kickoff": { label: "published after kickoff", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema (CB-005)" },
  "no_explicit_pick": { label: "no explicit pick", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "compact_section_hold": { aliasOf: "legal_hold", where: ["skipped"], shown: "renders as canonical label", spec: "Architect 2026-09-25" },
  "hold_no_typed_rows": { label: "on hold: text not yet transcribed", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "legal_hold": { label: "on hold pending legal review", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "legal_block": { label: "source can't be used (terms of use)", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "skip_marked": { label: "marked skip in review notes", where: ["skipped"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "manual_public_one_shot": { label: "one-time manual transcription", where: ["notes"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "enum_resolved": { label: "team or player added to our list", where: ["notes"], shown: "Not today (internal data); label ready if it ever goes public", spec: "non-schema" },
  "mapping_missing": { label: "not matched to a tracked topic", where: ["score status void"], shown: "Yes: /changelog In review entries", spec: "rubric-v1 (Architect 2026-09-25)" },
  "prints_disagree": { label: "official sources disagree", where: ["score status void"], shown: "Yes: /changelog In review entries", spec: "rubric-v1 (Architect 2026-09-25)" },
  "skipped_disagree": { aliasOf: "prints_disagree", where: ["scorer changelog"], shown: "renders as canonical label", spec: "Architect 2026-09-25" },
  "unit_mismatch": { label: "forecast and result use different units", where: ["unscorable_reason"], shown: "Yes: claim card, as \"None (label)\"", spec: "rubric-v1 (Architect 2026-09-25)" },
  "team_not_fbs_in_season": { label: "team was not in the top college division (FBS) that season", where: ["score status void"], shown: "Yes: /changelog In review entries", spec: "ncaa-fbs-team-ids-v1 v1.3.0 (Architect 2026-09-25)" },
};

const CODE_RE = /^[a-z0-9][a-z0-9_]*$/;
const has = (code) => Object.prototype.hasOwnProperty.call(REASON_LABELS, code);

/**
 * Extract the reason code from a raw reason value. Ingest sometimes writes "code: free-text detail"
 * (e.g. duplicate_forecast_cross_outlet: …); the code is the part before the first colon.
 */
export function reasonCodeOf(raw) {
  if (raw == null) return null;
  const s = String(raw).trim();
  if (!s) return null;
  const head = s.split(":")[0].trim();
  return CODE_RE.test(head) ? head : s;
}

/** Canonical code for a code (follows aliases); the code itself when it is not an alias or unknown. */
export function canonicalReasonCode(raw) {
  let code = reasonCodeOf(raw);
  const seen = new Set();
  while (code != null && has(code) && REASON_LABELS[code].aliasOf && !seen.has(code)) {
    seen.add(code);
    code = REASON_LABELS[code].aliasOf;
  }
  return code;
}

/** Plain label for a code (aliases render the canonical label), or the raw code when no label exists. */
export function reasonLabel(raw) {
  const code = reasonCodeOf(raw);
  if (code == null) return "";
  const canon = canonicalReasonCode(code);
  return has(canon) && REASON_LABELS[canon].label ? REASON_LABELS[canon].label : code;
}

export function hasReasonLabel(raw) {
  const code = reasonCodeOf(raw);
  if (code == null || !has(code)) return false;
  const canon = canonicalReasonCode(code);
  return has(canon) && !!REASON_LABELS[canon].label;
}

/**
 * { code, canonical, label, title } for rendering: show `label`, put `title` (the raw code as written in
 * the data) in the title attribute. `canonical` differs from `code` only for aliases.
 */
export function reasonDisplay(raw) {
  const code = reasonCodeOf(raw);
  if (code == null) return null;
  return { code, canonical: canonicalReasonCode(code), label: reasonLabel(code), title: code };
}
